#!/usr/bin/env ruby

require 'json'

v1baseurl = 'https://api.bitbucket.org/1.0'
v2baseurl = 'https://api.bitbucket.org/2.0'

def usage
    puts 'bitbucket-api version 1.0.0
        
usage: bitbucket-api -u username [command] [options]
        
COMMANDS:
  -u username
  --create-project teamname projectkey [options]
  --delete-project teamname projectkey
  --update-project teamname projectkey [options]
  --create-repository reponame [options]
  --delete-repository reponame
  --update-repository reponame [options]
  --set-group-privileges teamname groupname=value
  --set-user-privileges reponame acctname=value

OPTIONS:
  --options name=value,name=value,...

      is_private=boolean
      team=teamname
      project=projectkey
      project=projectname
      fork_policy=policyname'
end

# parse command-line arguments
if ARGV[0] != '-u'
    usage
    exit
else
    user, team, projectkey, repo, group, privilege, acct, action, httpmethod, owner = nil
    opts = Hash.new

    ARGV.each_with_index do |arg, i|
        case arg
            when '-u'
                user = ARGV[i+1]
            when '--create-project', '--delete-project', '--update-project'
                team = ARGV[i+1]
                projectkey = ARGV[i+2]
            when '--create-repository', '--delete-repository', '--update-repository'
                repo = ARGV[i+1]
            when '--set-group-privileges'
                team = ARGV[i+1]
                group, privilege = ARGV[i+2].split('=')
            when '--set-user-privileges'
                repo = ARGV[i+1]
                acct, privilege = ARGV[i+2].split('=')
            when '--options'
                opts = Hash[*ARGV[i+1].split(/,|=/)]
        end
    end

    ARGV.each do |arg|
        case arg
            when '--create-project'
                action = :createProject
                httpmethod = 'PUT'

                if opts["projectname"]
                    opts["name"] = opts["projectname"]
                    opts.delete("projectname")
                end
            when '--delete-project'
                action = :deleteProject
            when '--update-project'
                action = :updateProject
            when '--create-repository'
                action = :createRepo
                httpmethod = 'POST'

                team = opts["team"] if opts["team"]

                if opts["projectkey"]
                    if opts["project"] 
                        opts["project"]["key"] = opts["projectkey"]
                    else
                        opts["project"] = {"key" => opts["projectkey"]}
                    end

                    opts.delete("projectkey")
                end

                if opts["projectname"]
                    if opts["project"] 
                        opts["project"]["name"] = opts["projectname"]
                    else
                        opts["project"] = {"name" => opts["projectname"]}
                    end

                    opts.delete("projectname")
                end
            when '--delete-repository'
                action = :deleteRepo
            when '--update-repository'
                action = :updateRepo
            when '--set-group-privileges'
                action = :setGroupPrivileges

                case privilege
                    when 'delete'
                        httpmethod = 'DELETE'
                    when 'read', 'write', 'admin'
                        httpmethod = 'PUT'
                end
            when '--set-user-privileges'
                action = :setUserPrivileges

                if opts["team"]
                    owner = opts["team"]
                else
                    owner = user
                end

                case privilege
                    when 'delete'
                        httpmethod = 'DELETE'
                    when 'read', 'write', 'admin'
                        httpmethod = 'PUT'
                end
        end
    end

    case action
        when :createProject
            cmd = "curl -s -u #{user} -X #{httpmethod} -H \"Content-Type: application/json\" -d '#{opts.to_json}' #{v2baseurl}/teams/#{team}/projects/#{projectkey}" 
        when :deleteProject
        when :updateProject
        when :createRepo
            opts["scm"] = "git"

            if team
              # create a repo for a team
              cmd = "curl -s -u #{user} -X #{httpmethod} -H \"Content-Type: application/json\" -d '#{opts.to_json}' #{v2baseurl}/repositories/#{team}/#{repo.downcase}" 
            else
              # create a repo for a user
              cmd = "curl -s -u #{user} -X #{httpmethod} -H \"Content-Type: application/json\" -d '#{opts.to_json}' #{v2baseurl}/repositories/#{user}/#{repo.downcase}" 
            end
        when :deleteRepo
        when :updateRepo
        when :setGroupPrivileges
            if opts["reponame"]
              # set group privileges for a single team repo
                cmd = "curl -s -u #{user} -X #{httpmethod} #{v1baseurl}/group-privileges/#{team}/#{opts["reponame"]}/#{team}/#{group}" 
            else
              # set group privileges for all repos belonging to a team
                cmd = "curl -s -u #{user} -X #{httpmethod} #{v1baseurl}/group-privileges/#{team}/#{team}/#{group}" 
            end
        when :setUserPrivileges
            if repo and httpmethod == 'PUT'
                # set user read, write, admin privileges on 
                # single repo owned by owner
                cmd = "curl -s -u #{user} -X #{httpmethod} -d #{privilege} #{v1baseurl}/privileges/#{owner}/#{repo}/#{acct}" 
            end

            if repo and httpmethod == 'DELETE'
                # delete user privileges on 
                # single repo owned by owner
                cmd = "curl -s -u #{user} -X #{httpmethod} #{v1baseurl}/privileges/#{owner}/#{repo}/#{acct}" 
            end
        else
            usage
            exit
    end

    #puts cmd
    response = `#{cmd}`
    puts response
end
